name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Deploy to EC2 Server
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER_IP }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER_UBUNTU }}
        SSH_KEY: ${{ secrets.SSH_KEY_UBUNTU }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa $DEPLOY_SERVER >> ~/.ssh/known_hosts
        echo "$SSH_KEY" | tr -d '' > temp_key
        chmod 600 temp_key

        rsync -avz -e "ssh -i temp_key" ./ $DEPLOY_USER@$DEPLOY_SERVER:/home/$DEPLOY_USER/toko-online-python

        ssh -i temp_key $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
          cd ~/toko-online-python
          chmod +x setup.sh && ./setup.sh
          docker stop toko || true
          docker rm toko || true
          docker build -t toko-online-python .
          docker run -d --name toko -p 5000:5000 toko-online-python
        EOF
